source 'https://github.com/CocoaPods/Specs.git'

target :MendeleyKitiOSTests do
	platform :ios, '11.0'
    pod 'OCMock'
end

target :MendeleyKitOSXTests do
	platform :osx, '10.10'
    pod 'OCMock'
end
